dist: xenial   # required for Python >= 3.7
#sudo: required
language: python
python:
  - "2.7"
  - "3.6"
git:
  depth: 3
before_install:
  - sudo apt-get update
# command to install dependencies
# Travis CI Uses Isolated virtualenvs, so if you need to install Python packages, do it via pip and not apt
install:
  #- pip3 install --upgrade pip
  #- pip install -r requirements.txt # the --user option is mandatory if you are not using language: python
  - pwd
  - ls -la
  - orig_pwd=`pwd`
  - cd `mktemp -d`
  # 
  - git clone https://github.com/mozilla/OpenWPM.git --depth=1
  - cd OpenWPM
  - pip install --upgrade -r requirements.txt
  - ./install.sh --no-flash
  - cd ..
  # 
  - cp $orig_pwd/openwpm_setup.py setup.py
  - ls -la
  - python -c "from setuptools import find_packages; print find_packages()"
  - python -c "from setuptools import find_packages; print find_packages(exclude=['OpenWPM.test'])"
  - pip install .
  - pip show OpenWPM
  # 
  - cd $orig_pwd
# command to run tests
#before_script:
#  - flake8
script:
  - env
  - pwd
  - whoami
  - python -c "import sys; print sys.path"
  - python -c "from OpenWPM.automation import TaskManager; print TaskManager.load_default_params(1)"
  - wget https://raw.githubusercontent.com/mozilla/OpenWPM/master/demo.py -O demo.py
  - sed -i -e "/disable_flash/d" demo.py # we don't have flash
  - sed -i -e "s/http_instrument/headless/" demo.py # need to run headless
  - sed -i -e "s/from automation import/from OpenWPM.automation import/" demo.py
  - python demo.py
  #- pytest
  #- cd test
  #- py.test -s -v --durations=10 $TESTS
