dist: xenial   # required for Python >= 3.7
#sudo: required
language: python
python:
  - "2.7"
  - "3.6"
git:
  depth: 3
before_install:
  - sudo apt-get update
# command to install dependencies
# Travis CI Uses Isolated virtualenvs, so if you need to install Python packages, do it via pip and not apt
install:
  - ls -la
  #
  - ./install_openwpm.sh # install OpenWPM as a python module
  #
  - pip install --upgrade -r requirements.txt # install our python requirements
# command to run tests
before_script:
  - flake8
script:
  - env
  - pwd
  - whoami
  #
  - python -c "from OpenWPM.automation import TaskManager; print(TaskManager.load_default_params(1))"
  #
  - wget https://raw.githubusercontent.com/mozilla/OpenWPM/master/demo.py -O demo.py
  - sed -i -e 's/from automation import/from OpenWPM.automation import/' demo.py
  - sed -i -e 's/\['\''disable_flash'\''\] = False/['\''headless'\''\] = True/' demo.py # we don't have flash, and need to run headless
  #- sed -i -e 's/Desktop/openwpm_results/' demo.py # data_directory
  #- sed -i -e 's/Desktop/openwpm_results/' demo.py # log_directory
  #- sed -i -e 's/index='\''\*\*'\'')/)/' demo.py 
  - python demo.py
  #
  - python crawl.py
  #
  - ./analyze.sh
 
