dist: xenial   # required for Python >= 3.7
#sudo: required
language: python
python:
  - "2.7"
  - "3.6"
git:
  depth: 3
before_install:
  - sudo apt-get update
# command to install dependencies
# Travis CI Uses Isolated virtualenvs, so if you need to install Python packages, do it via pip and not apt
install:
  #- pip3 install --upgrade pip
  #- pip install -r requirements.txt # the --user option is mandatory if you are not using language: python
  - git clone https://github.com/mozilla/OpenWPM.git --depth=1
  - cd OpenWPM
  - pip install --upgrade -r requirements.txt
  - ./install.sh --no-flash
  - cd ..
  - ls -la /usr/lib
  - ls -la /usr/lib/python*
  - sudo mv OpenWPM /usr/lib/
  - for python_path in /usr/lib/python*; do sudo ln -s /usr/lib/OpenWPM ${python_path}/OpenWPM; done
  - for python_path in /usr/lib/python*; do ls -ld ${python_path}; done
  - for python_path in /usr/lib/python*; do ls -l ${python_path}; done
# command to run tests
#before_script:
#  - flake8
script:
  - env
  - pwd
  - cp /usr/lib/OpenWPM/demo.py demo.py
  - sed -i -e "/disable_flash/d" demo.py # we don't have flash
  - sed -i -e "s/http_instrument/headless/" demo.py # need to run headless
  - sed -i -e "s/from automation import/from OpenWPM.automation import/" demo.py
  - python demo.py
  #- pytest
  #- cd test
  #- py.test -s -v --durations=10 $TESTS
